name = "CopernicusUtils"
uuid = "428b1be5-cee6-4eca-9d02-b0da8dab1487"
version = "v1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Tensors = "48a634ad-e948-5137-8d70-aa71f2a747f4"

[compat]
julia = "1"
FileIO = "1"
NCDatasets = "0.9"
StaticArrays = "0.10, 0.11, 0.12"
Tensors = "1.0.1"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Test"]
